FederationEnvironment:
  DockerImage: null # null indicates to run Metis without docker, if it is provided then run using the specified image
  TerminationSignals:
    FederationRounds: 3 # only in synchronous execution
    ExecutionCutoffTimeMins: null
    MetricCutoffScore: 1.0
  EvaluationMetric: "accuracy"
  CommunicationProtocol:
    Name: "Synchronous"
    EnableSSL: True
  ModelStoreConfig:
    Name: "InMemory" # Others are "InMemory", "Redis"
    EvictionPolicy: "LineageLengthEviction" # Others are "NoEviction", "LineageLengthEviction"
    LineageLength: 1 # This field is only applicable if EvictionPolicy is set to "LineageLengthEviction"
  GlobalModelConfig:
    AggregationRule:
      Name: "FedAvg" # Others are FedAvg, FedStride, FedRec, PWA
      RuleSpecifications:
        ScalingFactor: "NumTrainingExamples" # Others are NUM_COMPLETED_BATCHES, NUM_PARTICIPANTS, NUM_TRAINING_EXAMPLES
    ParticipationRatio: 1
  LocalModelConfig:
    BatchSize: 32
    LocalEpochs: 4
    ValidationPercentage: 0.0
    OptimizerConfig:
      OptimizerName: "VanillaSGD"
      LearningRate: 0.05
      L2Reg: 0.0
  Controller:
    ProjectHome: "/projectmetis-rc"
    ConnectionConfigs:
      Hostname: "localhost"
      Username: "root"
      Password: "root"
      OnLogin: "source /etc/profile;"
    GRPCServicer:
      Hostname: "localhost"
      Port: 50051
    SSLConfigs:
      PrivateKey: "/projectmetis-rc/resources/ssl_config/default/server-key.pem"
      PublicCertificate: "/projectmetis-rc/resources/ssl_config/default/server-cert.pem"
  Learners:
    - LearnerID: "localhost-1"
      ProjectHome: "/projectmetis-rc"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Hostname: "localhost"
        Port: 50052
      SSLConfigs:
        PrivateKey: "/projectmetis-rc/resources/ssl_config/default/server-key.pem"
        PublicCertificate: "/projectmetis-rc/resources/ssl_config/default/server-cert.pem"
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
