FederationEnvironment:
  DockerImage: null # null indicates to run Metis without docker, if it is provided then run using the specified image
  TerminationSignals:
    FederationRounds: null # only in synchronous execution
    ExecutionCutoffTimeMins: 3
    MetricCutoffScore: 1.0
  EvaluationMetric: "accuracy"
  CommunicationProtocol:
    Name: "Asynchronous"
  HomomorphicEncryption: # homomorphic encryption scheme - if provided run with it, else disabled.
    Scheme: "CKKS" # Others are "CKKS" (a fully-homomorphic encryption scheme).
    BatchSize: 4096
    ScalingBits: 52
  GlobalModelConfig:
    AggregationRule:
      Name: "PWA" # Others are FedAvg, FedStride, FedRec, PWA
      RuleSpecifications:
        ScalingFactor: "NumTrainingExamples" # Others are NUM_COMPLETED_BATCHES, NUM_PARTICIPANTS, NUM_TRAINING_EXAMPLES
    ParticipationRatio: 1
  LocalModelConfig:
    BatchSize: 32
    LocalEpochs: 4
    ValidationPercentage: 0.0
    OptimizerConfig:
      OptimizerName: "VanillaSGD"
      LearningRate: 0.05
      L2Reg: 0.0
  Controller:
    ProjectHome: "/metisfl"
    ConnectionConfigs:
      Hostname: "localhost"
      Username: "root"
      Password: "root"
      OnLogin: "source /etc/profile;"
    GRPCServicer:
      Port: 50051
  Learners:
    - LearnerID: "localhost-1"
      ProjectHome: "/metisfl"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Port: 50052
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
    - LearnerID: "localhost-2"
      ProjectHome: "/metisfl"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Port: 50053
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
    - LearnerID: "localhost-3"
      ProjectHome: "/metisfl"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Port: 50054
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
    - LearnerID: "localhost-4"
      ProjectHome: "/metisfl"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Port: 50055
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
    - LearnerID: "localhost-5"
      ProjectHome: "/metisfl"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Port: 50056
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
    - LearnerID: "localhost-6"
      ProjectHome: "/metisfl"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Port: 50057
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
    - LearnerID: "localhost-7"
      ProjectHome: "/metisfl"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Port: 50058
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
    - LearnerID: "localhost-8"
      ProjectHome: "/metisfl"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Port: 50059
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
    - LearnerID: "localhost-9"
      ProjectHome: "/metisfl"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Port: 50060
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
    - LearnerID: "localhost-10"
      ProjectHome: "/metisfl"
      ConnectionConfigs:
        Hostname: "localhost"
        Username: "root"
        Password: "root"
        OnLogin: "source /etc/profile;"
      GRPCServicer:
        Port: 50061
      CudaDevices: [0]
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidationDatasetPath: ""
        TestDatasetPath: ""
